# call the name + description of the workflow

name: Django Project on Users Resources and Bookstore

# when do i want to run the commands
# wheneve someone pushes
# on which --> branche ?
on:
  push:
    branches:
      - main

# which --Jobs-- do i want to run
# write a list of jobs
# on which platform do i want to run the jobs
# define the steps to follow = process done at local repository
jobs:
    build:
      runs-on: ubuntu-latest
      steps: 
        -name: Checkout repository
        uses: actions/checkout@v2       # default library

        # set up Python
        -name: Set up Python
        uses: actions/setup-python@v2   # default library 
        with:
          python-version: 3.11           # version of python free to choose




# when someone does a pull request
on:
  pull_request: