# call the name + description of the workflow

name: Django Project on Users Resources and Bookstore

# when do i want to run the commands
# wheneve someone pushes
# on which --> branche ?
on:
  push:
    branches:
      - main

# which --Jobs-- do i want to run
# write a list of jobs
# on which platform do i want to run the jobs
# define the steps to follow = process done at local repository
jobs:
    build:
      runs-on: ubuntu-latest
      environment: my_project.env
      steps: 
        - name: Checkout repository
          uses: actions/checkout@v2       # default library

        # set up Python
        - name: Set up Python
          uses: actions/setup-python@v2   # default library 
          with:
            python-version: 3.11          # version of python free to choose

        # install -- dependencies -- & -- libraries --
        - name: Install dependencies and Libraries
          run: |                                      # run the following commands with pipe character
            python -m pip install --upgrade pip
            pip install -r requirements/dev.txt

        # run the tests -- UNIT TESTS --
        # copy the command from the local repository at MAKEFILE --
        - name: Run test
          run: |
            make dev-test2

        # add Database connection
          env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PWD: ${{ secrets.DB_PWD }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}


# when someone does a pull request
# on:
#   pull_request: